import React from 'react'

export default function Bai6() {
  return (
    <div>
      <div className='w-[500px] h-[200px] overflow-auto'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente iure sint quia ratione ad officiis dolorum voluptates consequuntur saepe neque quaerat, vitae veniam mollitia ab in consequatur eius rerum laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio ipsum qui, quisquam blanditiis soluta a delectus excepturi nam debitis temporibus! Inventore sapiente cupiditate odio maiores. Consequuntur voluptas provident laudantium animi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi animi expedita odio cupiditate, consequuntur ipsum repellat iusto, qui aut reiciendis culpa ipsam reprehenderit non debitis laborum alias corporis perspiciatis iure! Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis ipsam tempora deserunt eaque unde inventore natus aliquid in, sit qui asperiores a
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia delectus aut magnam eius, corrupti dolor velit fugit dolores deleniti ipsam laudantium aperiam odit quod vero similique neque praesentium quam deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, unde expedita, veniam suscipit nisi laudantium ipsam ullam ducimus atque itaque illo? Omnis nemo excepturi vitae modi fugit voluptate perferendis et. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae vel voluptate, recusandae illum veniam laborum, porro sit cupiditate quas iusto omnis, dolores labore! Voluptatibus fugiat repellat repellendus? Velit, possimus unde? Lorem ipsum dolor, sit amet consectetur adipisicing elit. Non quisquam suscipit maiores placeat officiis corporis, odio ratione provident tenetur, laboriosam officia exercitationem totam adipisci facilis perspiciatis possimus blanditiis error earum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus consectetur cupiditate, sapiente nisi asperiores incidunt aut temporibus pariatur minus veniam nemo officiis adipisci, quasi explicabo nulla enim odio similique unde.l Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus voluptatem ex explicabo, placeat eaque amet aut ut vitae quis, sint quam veritatis. Saepe deleniti provident ad voluptatem inventore suscipit aliquid. t hic ullam, ut, laboriosam sapiente velit aliquam. Natus!   </div>
    </div>
  )
}
